export const stockData = [
  {
    company: "Twitter Inc",
    ticker: "TWTR",
    stockPrice: "22.76 USD",
    timeElapsed: "5 sec ago",
    image:
      "https://www.waitrose.com/content/dam/waitrose/cellar/design/icons/twitter.png",
  },
  {
    company: "Square Inc",
    ticker: "SQ",
    stockPrice: "45.28 USD",
    timeElapsed: "10 sec ago",
    image: "../square.png",
  },
  {
    company: "Shopify Inc",
    ticker: "SHOP",
    stockPrice: "341.79 GBP",
    timeElapsed: "3 sec ago",
    image: "../shopify.png",
  },
  {
    company: "Sunrun Inc",
    ticker: "RUN",
    stockPrice: "9.87 USD",
    timeElapsed: "4 sec ago",
    image: "../Sunrun-Logo.png",
  },
  {
    company: "Adobe Inc",
    ticker: "ADBE",
    stockPrice: "300.99 USD",
    timeElapsed: "10 sec ago",
    image: "../Adobe-Logo.png",
  },
  {
    company: "HubSpot Inc",
    ticker: "HUBS",
    stockPrice: "115.22 USD",
    timeElapsed: "12 sec ago",
    image: "../hubspot.png",
  },
  {
    company: "Facebook",
    ticker: "FB",
    stockPrice: "415.22 USD",
    timeElapsed: "15 sec ago",
    image: "../facebook.jpeg",
  },
  {
    company: "JP Morgan",
    ticker: "JP",
    stockPrice: "415.92 USD",
    timeElapsed: "55 sec ago",
    image: "../JPmorgan.png",
  },
  {
    company: "Tesla",
    ticker: "TS",
    stockPrice: "499.92 USD",
    timeElapsed: "36 sec ago",
    image: "../TeslaLogo.png",
  },
  {
    company: "JD Sports",
    ticker: "JD",
    stockPrice: "415.92 GBP",
    timeElapsed: "33 sec ago",
    image: "../JDsports.png",
  },
  {
    company: "Ticketmaster",
    ticker: "TM",
    stockPrice: "41.92 USD",
    timeElapsed: "35 sec ago",
    image: "../TMlogo.png",
  },
];
